Repository APP-Android2/FinalProject-ApartTalk, pull requests merged in 2024-05, with the labels that each got.

#1 [feat] Create README.md
  README.md
Labels: UI

#4 #3 feat splashscreen 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/MainActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/SplashScreenActivity.kt
  app/src/main/res/drawable/aparttalk.gif
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: UI

#10 8 feat 아이콘 추가하기
  app/src/main/res/drawable/icon_back.xml
  app/src/main/res/drawable/icon_bell.xml
  app/src/main/res/drawable/icon_chat.xml
  app/src/main/res/drawable/icon_edit.xml
  app/src/main/res/drawable/icon_facility.xml
  app/src/main/res/drawable/icon_home.xml
  app/src/main/res/drawable/icon_location.xml
  app/src/main/res/drawable/icon_menu.xml
  app/src/main/res/drawable/icon_search.xml
Labels: UI

#18 #17 feat 전체 화면 구현
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/entiremenu/EntireMenuFragment.kt
  app/src/main/res/drawable/icon_customer_service.xml
  app/src/main/res/drawable/icon_next.xml
  app/src/main/res/drawable/icon_reservation.xml
  app/src/main/res/drawable/icon_writeletter.xml
  app/src/main/res/drawable/image_aparttalk.png
  app/src/main/res/drawable/outline_settings_24.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_entire_menu.xml
  app/src/main/res/menu/menu_setting.xml
  app/src/main/res/values/colors.xml
Labels: UI

#24 #19 feat 주변시설 화면 구성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/model/LocationAllData.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/model/LocationExtraData.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/AllLocationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/CafeLocationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/FoodLocationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/HospitalLacationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/LocationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/LocationShowActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/PharmacyLocationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/adapter/AllAdapter.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/adapter/ExtraAdapter.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/adapter/LocationAdapter.kt
  app/src/main/res/layout/activity_location_show.xml
  app/src/main/res/layout/fragment_all_location.xml
  app/src/main/res/layout/fragment_cafe_location.xml
  app/src/main/res/layout/fragment_entire_menu.xml
  app/src/main/res/layout/fragment_food_location.xml
  app/src/main/res/layout/fragment_hospital_lacation.xml
  app/src/main/res/layout/fragment_location.xml
  app/src/main/res/layout/fragment_pharmacy_location.xml
  app/src/main/res/layout/item_all_menu.xml
  app/src/main/res/layout/item_extra_menu.xml
Labels: UI

#36 25 feat 이용시설 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/model/FacilityData.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/entiremenu/EntireMenuFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/facility/DetailFacilityActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/facility/FacReservationActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/facility/FacilityFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/facility/adapter/DetailViewPagerAdapter.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/facility/adapter/FacilityAdapter.kt
  app/src/main/res/drawable/icon_error_circle.xml
  app/src/main/res/drawable/test_facility.png
  app/src/main/res/layout/activity_detail_facility.xml
  app/src/main/res/layout/activity_fac_reservation.xml
  app/src/main/res/layout/detail_list_item.xml
  app/src/main/res/layout/dropdown_item.xml
  app/src/main/res/layout/fragment_entire_menu.xml
  app/src/main/res/layout/fragment_facility.xml
  app/src/main/res/layout/fragment_location.xml
  app/src/main/res/layout/item_facility_grid.xml
  app/src/main/res/values/strings.xml
Labels: UI

#41 #38 feat 설정 화면 작업 및 삭제
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/entiremenu/CompanyInfoActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/entiremenu/EntireMenuFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/entiremenu/PrivacyPolicyActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/entiremenu/UserAgreementActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/facility/DetailFacilityActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/facility/FacReservationActivity.kt
  app/src/main/res/layout/activity_company_info.xml
  app/src/main/res/layout/activity_detail_facility.xml
  app/src/main/res/layout/activity_privacy_policy.xml
  app/src/main/res/layout/activity_user_agreement.xml
  app/src/main/res/layout/fragment_entire_menu.xml
  app/src/main/res/layout/fragment_facility.xml
  app/src/main/res/values/strings.xml
Labels: UI

#44 #43 feat 화면 수정 작업
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/entiremenu/EntireMenuFragment.kt
  app/src/main/res/drawable/aparttalkcompany.gif
  app/src/main/res/layout/activity_company_info.xml
  app/src/main/res/layout/activity_privacy_policy.xml
  app/src/main/res/layout/activity_user_agreement.xml
Labels: UI

#50 #9 Feat Login 화면
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/SplashScreenActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/login/ApartmentAdapter.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/login/ApartmentBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/login/DatePickerDialogFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/login/Login2Fragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/login/LoginActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/login/PermissionBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/login/SignUp1Fragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/login/SignUp2Fragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/login/SignUp3Fragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/login/SignUp4Fragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/login/SignUpActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/login/SignUpViewModel.kt
  app/src/main/res/anim/slide_in_left.xml
  app/src/main/res/anim/slide_in_right.xml
  app/src/main/res/anim/slide_out_left.xml
  app/src/main/res/anim/slide_out_right.xml
  app/src/main/res/color/checkbox_icon_tint.xml
  app/src/main/res/color/checkbox_tint.xml
  app/src/main/res/drawable/circle.xml
  app/src/main/res/drawable/google.png
  app/src/main/res/drawable/google_login.png
  app/src/main/res/drawable/icon_call.xml
  app/src/main/res/drawable/icon_distance.xml
  app/src/main/res/drawable/icon_forward.xml
  app/src/main/res/drawable/icon_image.xml
  app/src/main/res/drawable/icon_notifications_active.xml
  app/src/main/res/drawable/icon_phone_android.xml
  app/src/main/res/drawable/icon_photo_camera.xml
  app/src/main/res/drawable/icon_smartphone.xml
  app/src/main/res/drawable/image_aparttak2.png
  app/src/main/res/drawable/kakao_login.png
  app/src/main/res/drawable/large_top_rounding.xml
  app/src/main/res/drawable/naverlogin.png
  app/src/main/res/drawable/outline_settings_24.xml
  app/src/main/res/drawable/search_off.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_apartment_bottom_sheet.xml
  app/src/main/res/layout/fragment_date_picker_dialog.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_login2.xml
  app/src/main/res/layout/fragment_permission_bottom_sheet.xml
  app/src/main/res/layout/fragment_sign_up1.xml
  app/src/main/res/layout/fragment_sign_up2.xml
  app/src/main/res/layout/fragment_sign_up3.xml
  app/src/main/res/layout/fragment_sign_up4.xml
  app/src/main/res/layout/item_apartment.xml
  app/src/main/res/navigation/nav_login.xml
  app/src/main/res/navigation/nav_signup.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: 기능, UI

#55 #53 refactor 전체적인 화면 수정 및 화면 연결
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/community/fragment/CommunityAddFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/community/fragment/CommunityModifyFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/entiremenu/AptSchedule/AptScheduleActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/entiremenu/EntireMenuFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/entiremenu/FireCheck/FireCheckMainFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/facility/FacReservationActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/util/DialogConfirm.kt
  app/src/main/res/layout/activity_apt_schedule.xml
  app/src/main/res/layout/fragment_apt_schedule_show_bottom_sheet.xml
  app/src/main/res/layout/fragment_entire_menu.xml
  app/src/main/res/layout/fragment_fire_check_main.xml
  app/src/main/res/layout/fragment_fire_check_self.xml
  app/src/main/res/layout/fragment_info.xml
  app/src/main/res/layout/fragment_inquiry.xml
  app/src/main/res/layout/fragment_inquiry_write.xml
  app/src/main/res/layout/fragment_survey_list.xml
  app/src/main/res/layout/fragment_user_info_bottom_sheet_dialog.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: UI

#60 #58 fix 전체 화면 및 이용 시설 화면 수정
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/facility/adapter/FacilityAdapter.kt
  app/src/main/res/drawable/icon_logout.xml
  app/src/main/res/layout/activity_detail_facility.xml
  app/src/main/res/layout/activity_fac_reservation.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_entire_menu.xml
  app/src/main/res/layout/item_facility_grid.xml
Labels: UI

#77 #75 feat 화면 연결
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/entiremenu/EntireMenuFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/home/fragment/HomeFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/info/InfoFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/mywrite/MyWriteActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/mywrite/MyWriteFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/reservation/ReservationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/reservation/ReserveActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/service/ServiceActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/service/ServiceFragment.kt
  app/src/main/res/layout/activity_info.xml
  app/src/main/res/layout/activity_my_write.xml
  app/src/main/res/layout/activity_reserve.xml
  app/src/main/res/layout/activity_service.xml
  app/src/main/res/layout/fragment_entire_menu.xml
  app/src/main/res/layout/fragment_home.xml
Labels: 리팩토링, UI

#85 #81 feat 주변 편의시설 연결
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/entiremenu/EntireMenuFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/home/fragment/HomeFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/LocationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/vote/VoteActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/vote/VoteFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/vote/VoteTabFragment.kt
  app/src/main/res/layout/activity_vote.xml
  app/src/main/res/layout/fragment_vote.xml
Labels: 리팩토링, UI

#90 #86 refactor 코드 수정
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/MainActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/home/fragment/HomeFragment.kt
Labels: UI

#99 #91 feat 방문 주차 예약 화면 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/entiremenu/EntireMenuFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/home/fragment/HomeFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/parking/ParkingActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/parking/ParkingCheckFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/parking/ParkingReserveFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/parking/adapter/ParkingCheckAdapter.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/parking/adapter/ParkingReserveAdapter.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/util/FragmentUtil.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_parking.xml
  app/src/main/res/layout/fragment_parking_check.xml
  app/src/main/res/layout/fragment_parking_reserve.xml
  app/src/main/res/layout/row_parking_reserve.xml
Labels: UI

#107 #103 feat 카카오 키값 숨기기 및 패키지 생성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/db/FacilityDataSource.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/model/FacilityModel.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/model/ResultKeyWordModel.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/repository/FacilityRepository.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/facility/FacilityFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/facility/adapter/FacilityAdapter.kt
  settings.gradle.kts
Labels: 기능

#112 #108 feat 주변 시설 데이터 받아오기 구현
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/SplashScreenActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/db/FacilityDataSource.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/db/LocationDataSource.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/model/KakaoApi.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/repository/FacilityRepository.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/repository/LocationRepository.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/AllLocationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/CafeLocationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/FoodLocationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/HospitalLacationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/PharmacyLocationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/adapter/AllAdapter.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/adapter/ExtraAdapter.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/viewmodel/EachLocationViewModel.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/viewmodel/LocationViewModel.kt
  app/src/main/res/layout/activity_splash_screen.xml
Labels: 기능

#115 #114 feat 주변 시설 상세 보기 구현
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/AllLocationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/CafeLocationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/FoodLocationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/HospitalLacationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/LocationShowActivity.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/PharmacyLocationFragment.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/adapter/AllAdapter.kt
  app/src/main/java/kr/co/lion/application/finalproject_aparttalk/ui/location/adapter/ExtraAdapter.kt
Labels: 기능
